/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_cgvis_moscalc_SmallCalc */

#ifndef _Included_de_cgvis_moscalc_SmallCalc
#define _Included_de_cgvis_moscalc_SmallCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_cgvis_moscalc_SmallCalc
 * Method:    calc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_cgvis_moscalc_SmallCalc_calc
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
